@BASE_URL = http://localhost:3001/api
#@BASE_URL = https://gentle-everglades-54735.herokuapp.com/api

###

GET {{BASE_URL}}/persons HTTP/1.1
Content-type: application/json

####

GET {{BASE_URL}}/persons/2 HTTP/1.1
Content-type: application/json

####

GET {{BASE_URL}}/persons/5 HTTP/1.1
Content-type: application/json

####

DELETE {{BASE_URL}}/persons/2 HTTP/1.1
Content-type: application/json

####

POST {{BASE_URL}}/persons HTTP/1.1
Content-type: application/json

{
  "name": "Aku Ankka",
  "number": "050-123456"
}

####

POST {{BASE_URL}}/persons HTTP/1.1
Content-type: application/json

{
  "number": "050-123456"
}

####

POST {{BASE_URL}}/persons HTTP/1.1
Content-type: application/json

{
  "name": "Roope Ankka"
}
