@BASE_URL = http://localhost:3003/api

###

# @name getAll
GET {{BASE_URL}}/blogs HTTP/1.1
Content-type: application/json

####

# @name create
POST {{BASE_URL}}/blogs HTTP/1.1
Content-type: application/json

{
  "title": "React v16.8: The One With Hooks",
  "author": "Dan Abramov",
  "url": "https://reactjs.org/blog/2019/02/06/react-v16.8.0.html",
  "likes": 0
}

####

# @name update
PUT {{BASE_URL}}/blogs/{{getAll.response.body.8.id}} HTTP/1.1
Content-type: application/json

{
  "title": "{{getAll.response.body.8.title}}",
  "author": "{{getAll.response.body.8.author}}",
  "url": "{{getAll.response.body.8.url}}",
  "likes": 12
}

####

# @name delete
DELETE {{BASE_URL}}/blogs/{{getAll.response.body.9.id}} HTTP/1.1
Content-type: application/json

###

# @name listUsers
GET {{BASE_URL}}/users HTTP/1.1
Content-type: application/json

###

# @name createUser
POST {{BASE_URL}}/users HTTP/1.1
Content-type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpass"
}
